export const suddenLeaveConstants = {
  GET_ALL_SUDDEN_LEAVES_REQUEST: "GET_ALL_SUDDEN_LEAVES_REQUEST",
  GET_ALL_SUDDEN_LEAVES_SUCCESS: "GET_ALL_SUDDEN_LEAVES_SUCCESS",
  GET_ALL_SUDDEN_LEAVES_FAILURE: "GET_ALL_SUDDEN_LEAVES_FAILURE",

  GET_SUDDEN_LEAVE_REQUEST: "GET_SUDDEN_LEAVE_REQUEST",
  GET_SUDDEN_LEAVE_SUCCESS: "GET_SUDDEN_LEAVE_SUCCESS",
  GET_SUDDEN_LEAVE_FAILURE: "GET_SUDDEN_LEAVE_FAILURE",

  GET_USER_SUDDEN_LEAVES_REQUEST: "GET_USER_SUDDEN_LEAVES_REQUEST",
  GET_USER_SUDDEN_LEAVES_SUCCESS: "GET_USER_SUDDEN_LEAVES_SUCCESS",
  GET_USER_SUDDEN_LEAVES_FAILURE: "GET_USER_SUDDEN_LEAVES_FAILURE",

  SET_SUDDEN_LEAVE_REQUEST: "SET_SUDDEN_LEAVE_REQUEST",
  SET_SUDDEN_LEAVE_SUCCESS: "SET_SUDDEN_LEAVE_SUCCESS",
  SET_SUDDEN_LEAVE_FAILURE: "SET_SUDDEN_LEAVE_FAILURE",
};
